# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v7
      - name: Process and Create Package Structure
        run: |
            sudo apt install r-cran-knitr graphviz imagemagick 
            sudo apt install texlive-latex-extra
            sudo apt install weasyprint
            mkdir -p ~/.local/bin
            /bin/bash -c "$(curl -fsSL https://github.com/mittelmark/tmdoc/releases/latest/download/install-tmdoc.sh)"
            export PATH="~/.local/bin:$PATH"
            echo "PATH=$PATH" >> $GITHUB_ENV
      - name: build package
        run: |
            make build pkg=tmdoc4r
            export VRS=`grep Version: tmdoc4r/DESCRIPTION | grep -oE '[.0-9]+'`
            echo "VRS=$VRS" >> $GITHUB_ENV
  
      - name: Upload Package Release files
        uses: actions/upload-artifact@v7
        with: 
          name: tmdoc4r_${{ env.VRS }}.tar.gz
          path: tmdoc4r_${{ env.VRS }}.tar.gz
